tglog:
  container.name: "tglog"
  heartbeat.cron: "0 0 10 * * *" # once a day at 10:00

tgbot:
  botToken: telegram_bot_token
  chatId: telegram_chat_id

logs:
  events:
    include: "error"
    exclude:

container:
  events:
    include: "*"
    exclude:
  names:
    include: "*"
    exclude:

containers:
  container:
    - name: "some container name"
      logs:
        events:
          include: "error"
          exclude:
      container:
        events:
          include: "*"
          exclude:
    - name: "another container name"
      logs:
        events:
          include: "error"
          exclude:
      container:
        events:
          include: "*"
          exclude:

