tgbot:
  botToken: telegram_bot_token
  chatId: telegram_chat_id

log:
  events:
    include: "error"
    exclude:

container:
  events:
    include: "*"
    exclude:
  names:
    include: "*"
    exclude:


